        -- Create the news_articles table
        CREATE TABLE public.news_articles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            url TEXT NOT NULL UNIQUE, -- Using URL as the natural unique key
            source_id TEXT NULL,
            source_name TEXT NULL,
            author TEXT NULL,
            title TEXT NOT NULL,
            description TEXT NULL,
            url_to_image TEXT NULL,
            published_at TIMESTAMPTZ NOT NULL,
            content TEXT NULL,
            category TEXT NOT NULL, -- Category assigned during fetch
            fetched_at TIMESTAMPTZ DEFAULT now() NOT NULL
        );

        -- Add comments to columns for clarity
        COMMENT ON COLUMN public.news_articles.url IS 'Unique URL of the news article, used as the primary identifier for upserts.';
        COMMENT ON COLUMN public.news_articles.published_at IS 'Original publication date and time of the article.';
        COMMENT ON COLUMN public.news_articles.category IS 'Category assigned during the fetch process (e.g., tech, econ).';
        COMMENT ON COLUMN public.news_articles.fetched_at IS 'Timestamp when the article was inserted or last updated in the database.';

        -- Create indexes for faster lookups based on common filtering/sorting criteria
        CREATE INDEX idx_news_articles_category ON public.news_articles(category);
        CREATE INDEX idx_news_articles_published_at ON public.news_articles(published_at DESC); -- Index for sorting by newest first

        -- Note: RLS policies and GRANTs are often managed separately or in different migration files,
        -- but enabling RLS itself can be done here if desired.
        -- ALTER TABLE public.news_articles ENABLE ROW LEVEL SECURITY;