// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixesbbpnhkbvqggmubof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZXNiYnBuaGtidnFnZ211Ym9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDYxNDUsImV4cCI6MjA1ODkyMjE0NX0.EePLUYO6s2w6tUCMMEz-aex-A8syg3K1srDlB5zS9RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);